<script setup>
import {computed,nextTick,ref,onMounted,onBeforeUnmount} from 'vue';
const token=ref(localStorage.admin_token||''),user=ref('a123456'),pass=ref(''),products=ref([]),orders=ref([]),chats=ref([]),categories=ref([]),users=ref([]),stats=ref({}),paymentMethods=ref([]),tab=ref('dashboard'),error=ref(''),currentChat=ref(null),chatMessages=ref([]),chatMessagesEl=ref(null),chatSearch=ref(''),chatFilter=ref('all'),serviceError=ref(''),reply=ref(''),replySending=ref(false),editing=ref(null),deleteTarget=ref(null),logoutPending=ref(false),form=ref({name:'',description:'',price:'',original_price:'',stock:0,sales:0,status:'on_sale',image_url:'',category_id:''}),notice=ref(''),orderSearch=ref(''),orderFilter=ref('all'),orderUpdating=ref(null),selectedOrder=ref(null),orderDetailLoading=ref(false),orderDetailError=ref(''),orderError=ref(''),paymentEditing=ref(null),paymentDeleteTarget=ref(null),paymentSaving=ref(false),paymentError=ref(''),paymentForm=ref({id:0,paytype:'',paytypetitle:'',ftitle:'',minmoney:100,maxmoney:50000,isonline:0,state:1,remark:'',configs_data:{}});
const categoryEditing=ref(null),categoryDeleteTarget=ref(null),categoryForm=ref({name:'',description:'',sort_order:0});
let chatPoll=null;
const api=async(r,o={})=>{o.headers={...(o.headers||{}),...(o.body instanceof FormData?{}:{'Content-Type':'application/json'}),Authorization:`Bearer ${token.value}`};const x=await fetch(`/api/?route=${r}`,o);const raw=await x.text();let d;try{d=JSON.parse(raw)}catch{throw Error(x.status>=500?`服务暂时不可用（HTTP ${x.status}），请稍后重试`:'服务响应格式异常，请稍后重试')}if(!x.ok)throw Error(d.error||'请求失败');return d};
const filteredChats=computed(()=>chats.value.filter(c=>(chatFilter.value==='all'||c.status===chatFilter.value)&&c.visitor_name.toLowerCase().includes(chatSearch.value.trim().toLowerCase())));
const openChatCount=computed(()=>chats.value.filter(c=>c.status==='open').length);
const unreadTotal=computed(()=>chats.value.reduce((sum,c)=>sum+Number(c.unread_count||0),0));
const orderStatusLabels={pending:'待付款',paid:'已付款',delivering:'交付中',completed:'已完成',cancelled:'已取消',refunded:'已退款'};
const paymentStatusLabels={unpaid:'待付款',submitted:'待确认',confirmed:'已确认',failed:'已关闭'};
const orderTransitions={pending:'paid',paid:'delivering',delivering:'completed'};
const orderActionLabels={pending:'确认付款',paid:'开始交付',delivering:'完成订单'};
const filteredOrders=computed(()=>{const keyword=orderSearch.value.trim().toLowerCase();return orders.value.filter(o=>(orderFilter.value==='all'||o.status===orderFilter.value)&&(!keyword||[o.order_no,o.contact_name,o.contact_phone].some(value=>String(value||'').toLowerCase().includes(keyword))));});
const orderCounts=computed(()=>orders.value.reduce((counts,o)=>{counts.all++;if(Object.prototype.hasOwnProperty.call(counts,o.status))counts[o.status]++;return counts},{all:0,pending:0,paid:0,delivering:0,completed:0,cancelled:0,refunded:0}));
const paymentTypes=[{value:'alipay',label:'支付宝 (alipay)'},{value:'weixin',label:'微信支付 (weixin)'},{value:'linepay',label:'银行卡转账 (linepay)'},{value:'USDT',label:'USDT (USDT)'},{value:'EpUSDT',label:'EpUSDT 在线支付 (EpUSDT)'}];
const availablePaymentTypes=computed(()=>paymentTypes.map(type=>({...type,disabled:paymentEditing.value==='new'&&paymentMethods.value.some(item=>item.paytype===type.value)})));
function orderStatusLabel(status){return orderStatusLabels[status]||status||'未知状态'}
function orderActionLabel(status){return orderActionLabels[status]||''}
function paymentStatusLabel(status){return paymentStatusLabels[status]||'待付款'}
function formatMoney(value){return Number(value||0).toFixed(2)}
function formatDate(value){if(!value)return '—';const date=new Date(String(value).replace(' ','T')+'Z');return Number.isNaN(date.getTime())?value:date.toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).replace(/\//g,'-')}
async function login(){try{const d=await api('admin/login',{method:'POST',body:JSON.stringify({username:user.value,password:pass.value})});token.value=d.token;localStorage.admin_token=d.token;error.value='';await load()}catch(e){error.value=e.message}}
async function load(){const results=await Promise.allSettled([api('admin/products'),api('admin/orders'),api('admin/chats'),api('admin/stats'),api('admin/categories'),api('admin/users'),api('admin/payment-methods')]);const targets=[products,orders,chats,stats,categories,users,paymentMethods];const failed=[];results.forEach((result,index)=>{if(result.status==='fulfilled'){targets[index].value=result.value;if(index===1)orderError.value='';if(index===6)paymentError.value=''}else{const message=result.reason?.message||'数据加载失败';failed.push(message);if(index===1)orderError.value=message;if(index===6)paymentError.value=message}});if(failed.length)error.value=failed[0]}
async function reloadOrders(){orderError.value='';try{orders.value=await api('admin/orders')}catch(e){orderError.value=e.message||'订单加载失败'}}
function formatChatTime(value){if(!value)return '';const date=new Date(value.replace(' ','T')+'Z');const now=new Date();return date.toDateString()===now.toDateString()?date.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}):date.toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'})}
function latestPreview(chat){if(!chat.latest_message)return chat.status==='open'?'等待客户消息':'会话已结束';return `${chat.latest_sender==='agent'?'我：':''}${chat.latest_message}`}
function scrollMessages(){const el=chatMessagesEl.value;if(el)el.scrollTop=el.scrollHeight}
async function loadChats(){const data=await api('admin/chats');chats.value=data;if(currentChat.value){const updated=data.find(c=>c.id===currentChat.value.id);if(updated)currentChat.value=updated}}
async function refreshCurrentChat(forceScroll=false){if(!currentChat.value)return;const el=chatMessagesEl.value,stickToBottom=forceScroll||!el||el.scrollHeight-el.scrollTop-el.clientHeight<80;chatMessages.value=await api(`admin/chats/${currentChat.value.id}/messages`);await api(`admin/chats/${currentChat.value.id}/read`,{method:'POST'});if(stickToBottom){await nextTick();scrollMessages()}}
async function openChat(chat){currentChat.value=chat;serviceError.value='';try{await refreshCurrentChat(true);await loadChats()}catch(e){serviceError.value=e.message||'会话加载失败'}}
async function openService(){tab.value='service';serviceError.value='';try{await loadChats();if(currentChat.value){await refreshCurrentChat(true);await loadChats()}else if(chats.value.length)await openChat(chats.value[0])}catch(e){serviceError.value=e.message||'客服数据加载失败'}}
async function sendReply(){const content=reply.value.trim();if(!currentChat.value||!content||replySending.value||currentChat.value.status==='closed')return;replySending.value=true;serviceError.value='';try{await api(`admin/chats/${currentChat.value.id}/messages`,{method:'POST',body:JSON.stringify({content})});reply.value='';await Promise.all([refreshCurrentChat(true),loadChats()])}catch(e){serviceError.value=e.message||'回复发送失败'}finally{replySending.value=false}}
async function advance(order){const next=orderTransitions[order.status];if(!next||orderUpdating.value===order.id)return;orderUpdating.value=order.id;orderError.value='';try{await api(`admin/orders/${order.id}/status`,{method:'POST',body:JSON.stringify({status:next})});await reloadOrders();if(selectedOrder.value?.id===order.id){const latest=orders.value.find(item=>item.id===order.id);if(latest)await openOrder(latest);else selectedOrder.value=null}}catch(e){orderError.value=e.message||'订单状态更新失败'}finally{orderUpdating.value=null}}
async function openOrder(order){selectedOrder.value={...order,items:[]};orderDetailLoading.value=true;orderDetailError.value='';try{selectedOrder.value=await api(`admin/orders/${order.id}`)}catch(e){orderDetailError.value=e.message||'订单详情加载失败'}finally{orderDetailLoading.value=false}}
function editProduct(p){editing.value=p.id;form.value={name:p.name,description:p.description||'',price:p.price,original_price:p.original_price??'',stock:p.stock,sales:p.sales??0,status:p.status,image_url:p.image_url||'',category_id:p.category_id||''}}
function newProduct(){editing.value='new';form.value={name:'',description:'',price:'',original_price:'',stock:0,sales:0,status:'on_sale',image_url:'',category_id:''}}
function newCategory(){categoryEditing.value='new';categoryForm.value={name:'',description:'',sort_order:categories.value.length+1}}
function editCategory(c){categoryEditing.value=c.id;categoryForm.value={name:c.name,description:c.description||'',sort_order:c.sort_order||0}}
async function saveCategory(){if(!categoryForm.value.name.trim())return;try{const route=categoryEditing.value==='new'?'admin/categories':`admin/categories/${categoryEditing.value}/save`;await api(route,{method:'POST',body:JSON.stringify(categoryForm.value)});categoryEditing.value=null;notice.value='分类已保存';await load()}catch(e){error.value=e.message}}
async function confirmCategoryDelete(){if(!categoryDeleteTarget.value)return;try{await api(`admin/categories/${categoryDeleteTarget.value.id}/delete`,{method:'POST'});categoryDeleteTarget.value=null;await load()}catch(e){error.value=e.message}}
async function uploadImage(e){const file=e.target.files?.[0];if(!file)return;const data=new FormData();data.append('image',file);try{const result=await api('admin/products/upload',{method:'POST',body:data});form.value.image_url=result.url}catch(err){error.value=err.message}e.target.value=''}
async function saveProduct(){const method='POST';const route=editing.value==='new'?'admin/products':`admin/products/${editing.value}/save`;try{await api(route,{method,body:JSON.stringify(form.value)});editing.value=null;notice.value='商品已保存';await load()}catch(e){error.value=e.message}}
function removeProduct(p){deleteTarget.value=p}
async function confirmDelete(){if(!deleteTarget.value)return;await api(`admin/products/${deleteTarget.value.id}/delete`,{method:'POST'});deleteTarget.value=null;await load()}
async function loadPaymentMethods(){paymentError.value='';try{paymentMethods.value=await api('admin/payment-methods')}catch(e){paymentError.value=e.message||'充值方式加载失败'}}
async function openPayments(){tab.value='payments';await loadPaymentMethods()}
function newPaymentMethod(){paymentEditing.value='new';paymentError.value='';paymentForm.value={id:0,paytype:'',paytypetitle:'',ftitle:'',minmoney:100,maxmoney:50000,isonline:0,state:1,remark:'',configs_data:{}}}
function editPaymentMethod(item){paymentEditing.value=item.id;paymentError.value='';paymentForm.value={id:item.id,paytype:item.paytype,paytypetitle:item.paytypetitle,ftitle:item.ftitle||'',minmoney:Number(item.minmoney??100),maxmoney:Number(item.maxmoney??50000),isonline:item.paytype==='EpUSDT'?1:Number(item.isonline||0),state:Number(item.state||0),remark:item.remark||'',configs_data:{...(item.configs_data||{})}}}
function changePaymentType(){paymentForm.value.configs_data={};if(paymentForm.value.paytype==='EpUSDT'){paymentForm.value.isonline=1;if(!paymentForm.value.paytypetitle)paymentForm.value.paytypetitle='EpUSDT'}}
async function savePaymentMethod(){const value=paymentForm.value;paymentError.value='';if(!value.paytype||!value.paytypetitle.trim()){paymentError.value='请选择支付标识并填写支付名称';return}if(Number(value.minmoney)<0||Number(value.maxmoney)<Number(value.minmoney)){paymentError.value='最高金额不能低于最低金额';return}if(value.paytype==='EpUSDT'&&!/^T[1-9A-HJ-NP-Za-km-z]{33}$/.test((value.configs_data.trc20||'').trim())){paymentError.value='请输入有效的 TRC20 收款地址';return}paymentSaving.value=true;try{const route=paymentEditing.value==='new'?'admin/payment-methods':`admin/payment-methods/${paymentEditing.value}/save`;await api(route,{method:'POST',body:JSON.stringify(value)});paymentEditing.value=null;notice.value='充值方式已保存';await loadPaymentMethods()}catch(e){paymentError.value=e.message||'保存失败'}finally{paymentSaving.value=false}}
async function togglePaymentState(item){const previous=Number(item.state),next=previous===1?0:1;item.state=next;paymentError.value='';try{await api(`admin/payment-methods/${item.id}/status`,{method:'POST',body:JSON.stringify({state:next})})}catch(e){item.state=previous;paymentError.value=e.message||'状态更新失败'}}
async function confirmPaymentDelete(){if(!paymentDeleteTarget.value)return;paymentError.value='';try{await api(`admin/payment-methods/${paymentDeleteTarget.value.id}/delete`,{method:'POST'});paymentDeleteTarget.value=null;await loadPaymentMethods()}catch(e){paymentError.value=e.message||'删除失败';paymentDeleteTarget.value=null}}
async function uploadPaymentQr(e){const file=e.target.files?.[0];if(!file)return;const data=new FormData();data.append('image',file);paymentError.value='';try{const result=await api('admin/payment-methods/upload',{method:'POST',body:data});paymentForm.value.configs_data.ewmurl=result.url}catch(err){paymentError.value=err.message||'二维码上传失败'}e.target.value=''}
async function closeChat(c){const status=c.status==='closed'?'open':'closed';serviceError.value='';try{await api(`admin/chats/${c.id}/status`,{method:'POST',body:JSON.stringify({status})});await loadChats();if(currentChat.value?.id===c.id)currentChat.value={...currentChat.value,status}}catch(e){serviceError.value=e.message||'会话状态更新失败'}}
function requestLogout(){logoutPending.value=true}
function logout(){localStorage.removeItem('admin_token');token.value='';pass.value='';logoutPending.value=false;tab.value='dashboard'}
if(token.value)load();
onMounted(()=>{chatPoll=setInterval(async()=>{if(token.value&&tab.value==='service'){try{await refreshCurrentChat();await loadChats()}catch{}}},3000)});
onBeforeUnmount(()=>{if(chatPoll)clearInterval(chatPoll)});
</script>
<template>
  <section v-if="!token" class="login-page"><div class="login-art"><div class="logo-mark"><img src="/brand-mark.png" alt="闪购商城"></div><p class="eyebrow">LIGHTWEIGHT COMMERCE</p><h1>让每一次交易<br><span>都更有价值</span></h1><p>商品、订单与客户服务，一站式管理您的电商业务。</p><small>安全运营 · 高效协作 · 数据洞察</small></div><div class="login-card"><p class="kicker">ADMIN CONSOLE</p><h2>欢迎回来</h2><p class="hint">登录管理后台，开启高效运营</p><label>管理员账号</label><input v-model="user" placeholder="请输入管理员账号" autocomplete="username"><label>登录密码</label><input v-model="pass" type="password" placeholder="请输入密码" autocomplete="current-password" @keyup.enter="login"><button class="login-submit" @click="login">登录管理后台 <span>→</span></button><p class="login-error">{{error}}</p><div class="secure">⌁ 仅限授权管理员访问</div></div></section>
  <div v-else class="shell"><aside><h2 class="brand-lockup"><img src="/brand-mark.png" alt="" aria-hidden="true"><span>闪购商城</span></h2><button :class="{active:tab==='dashboard'}" @click="tab='dashboard'">工作台</button><button :class="{active:tab==='products'}" @click="tab='products'">商品管理</button><button :class="{active:tab==='categories'}" @click="tab='categories'">分类管理</button><button :class="{active:tab==='orders'}" @click="tab='orders'">订单管理</button><button :class="{active:tab==='users'}" @click="tab='users'">会员管理</button><button :class="{active:tab==='payments'}" @click="openPayments">支付管理</button><button :class="{active:tab==='service'}" @click="openService">在线客服 <span v-if="unreadTotal" class="nav-unread">{{unreadTotal>99?'99+':unreadTotal}}</span></button><div class="sidebar-actions"><button class="logout" @click="requestLogout">退出登录</button></div></aside><main><header class="page-head"><div><p class="crumb">ADMIN CONSOLE / {{tab}}</p><h1>{{({dashboard:'运营工作台',products:'商品管理',categories:'分类管理',orders:'订单管理',users:'会员管理',payments:'支付管理',service:'在线客服'})[tab]}}</h1></div><button class="refresh" @click="tab==='service'?openService():tab==='payments'?loadPaymentMethods():load()">刷新数据</button></header>
    <section v-if="tab==='dashboard'" class="cards"><div><span>在售商品</span><b>{{stats.products||0}}</b><small>当前可售商品</small></div><div><span>订单总数</span><b>{{stats.orders||0}}</b><small>累计订单</small></div><div><span>成交金额</span><b>${{Number(stats.revenue||0).toFixed(2)}}</b><small>已支付及履约订单</small></div><div><span>会员总数</span><b>{{stats.users||0}}</b><small>注册会员</small></div></section>
    <section v-if="tab==='dashboard'" class="dashboard-grid"><div class="panel"><h3>订单概况</h3><div class="order-status"><span>待处理 <b>{{stats.pending||0}}</b></span><span>客服会话 <b>{{chats.length}}</b></span></div></div><div class="panel"><h3>商品分类</h3><p v-for="c in categories" :key="c.name" class="category-row"><span>{{c.name}}</span><b>{{c.product_count}}</b></p></div></section>
    <section v-if="tab==='products'" class="panel"><div class="panel-toolbar"><h3>商品列表</h3><div><span>共 {{products.length}} 件</span><button class="primary" @click="newProduct">+ 新增商品</button></div></div><div class="table-wrap"><table><tr><th>名称</th><th>价格</th><th>库存</th><th>已售</th><th>状态</th><th>更新时间</th><th>操作</th></tr><tr v-for="p in products" :key="p.id"><td><strong>{{p.name}}</strong><small>{{p.description}}</small></td><td><strong>${{p.price}}</strong><del v-if="p.original_price">${{p.original_price}}</del></td><td>{{p.stock}}</td><td>{{p.sales??0}}</td><td><i :class="['status',p.status]">{{p.status==='on_sale'?'在售':'已下架'}}</i></td><td>{{p.updated_at||p.created_at}}</td><td><button class="action" @click="editProduct(p)">编辑</button><button class="danger" @click="removeProduct(p)">删除</button></td></tr></table></div></section>
    <section v-if="tab==='categories'" class="panel"><div class="panel-toolbar"><div><h3>分类列表</h3><span>共 {{categories.length}} 个分类</span></div><button class="primary" @click="newCategory">+ 新增分类</button></div><div class="table-wrap"><table><thead><tr><th>名称</th><th>描述</th><th>排序</th><th>商品数</th><th>操作</th></tr></thead><tbody><tr v-for="c in categories" :key="c.id"><td><strong>{{c.name}}</strong></td><td>{{c.description||'—'}}</td><td>{{c.sort_order}}</td><td>{{c.product_count}}</td><td><button class="action" @click="editCategory(c)">编辑</button><button class="danger" @click="categoryDeleteTarget=c">删除</button></td></tr></tbody></table></div></section>
    <div v-if="categoryEditing" class="modal-backdrop" @click.self="categoryEditing=null"><div class="modal-card category-modal"><div class="modal-head"><div><p class="modal-kicker">CATEGORY CONSOLE</p><h3>{{categoryEditing==='new'?'新增分类':'编辑分类'}}</h3></div><button class="modal-close" @click="categoryEditing=null">×</button></div><div class="editor-grid"><label>分类名称<input v-model="categoryForm.name" maxlength="80" placeholder="请输入分类名称"></label><label>排序<input v-model.number="categoryForm.sort_order" type="number" min="0"></label><label class="wide">分类描述<textarea v-model="categoryForm.description" maxlength="300" placeholder="请输入分类描述"></textarea></label></div><div class="modal-actions"><button class="ghost" @click="categoryEditing=null">取消</button><button class="primary" @click="saveCategory">保存分类</button></div></div></div>
    <div v-if="categoryDeleteTarget" class="modal-backdrop" @click.self="categoryDeleteTarget=null"><div class="modal-card confirm-modal"><div class="confirm-icon">!</div><h3>确认删除分类？</h3><p>删除“{{categoryDeleteTarget.name}}”后，该分类下商品会变为未分类。</p><div class="modal-actions"><button class="ghost" @click="categoryDeleteTarget=null">取消</button><button class="danger solid" @click="confirmCategoryDelete">确认删除</button></div></div></div>
    <section v-if="tab==='orders'" class="orders-page">
      <div class="order-summary"><button :class="{active:orderFilter==='all'}" @click="orderFilter='all'"><span>全部订单</span><b>{{orderCounts.all}}</b></button><button :class="{active:orderFilter==='pending'}" @click="orderFilter='pending'"><span>待付款</span><b>{{orderCounts.pending}}</b></button><button :class="{active:orderFilter==='paid'}" @click="orderFilter='paid'"><span>已付款</span><b>{{orderCounts.paid}}</b></button><button :class="{active:orderFilter==='delivering'}" @click="orderFilter='delivering'"><span>交付中</span><b>{{orderCounts.delivering}}</b></button><button :class="{active:orderFilter==='completed'}" @click="orderFilter='completed'"><span>已完成</span><b>{{orderCounts.completed}}</b></button></div>
      <section class="panel order-panel"><div class="panel-toolbar"><div><h3>订单列表</h3><span class="order-count">共 {{filteredOrders.length}} / {{orders.length}} 笔</span></div><div class="order-tools"><label class="order-filter"><span>状态</span><select v-model="orderFilter"><option value="all">全部</option><option value="pending">待付款</option><option value="paid">已付款</option><option value="delivering">交付中</option><option value="completed">已完成</option><option value="cancelled">已取消</option><option value="refunded">已退款</option></select></label><label class="order-search"><span>⌕</span><input v-model="orderSearch" placeholder="搜索订单号或联系人"></label></div></div><div v-if="orderError" class="order-error">{{orderError}} <button @click="reloadOrders">重试</button></div><div v-if="!filteredOrders.length" class="order-empty"><div>⌁</div><h3>{{orders.length?'没有符合条件的订单':'暂无订单'}}</h3><p>{{orders.length?'请调整筛选条件或搜索关键词':'新订单会在这里显示。'}}</p><button v-if="orderSearch||orderFilter!=='all'" class="ghost" @click="orderSearch='';orderFilter='all'">清除筛选</button></div><div v-else class="table-wrap"><table><thead><tr><th>订单号</th><th>金额</th><th>支付方式</th><th>联系人</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="o in filteredOrders" :key="o.id"><td><button class="order-link" @click="openOrder(o)">{{o.order_no}}</button><small>{{formatDate(o.created_at)}}</small></td><td><strong class="order-amount">${{formatMoney(o.total_amount)}}</strong></td><td class="order-payment-cell"><strong>{{o.payment_name||'—'}}</strong><small>{{paymentStatusLabel(o.payment_status)}}</small></td><td>{{o.contact_name||'在线客户'}}<small v-if="o.contact_phone">{{o.contact_phone}}</small></td><td><i class="status" :class="o.status">{{orderStatusLabel(o.status)}}</i></td><td class="order-actions"><button class="action order-detail-button" @click="openOrder(o)">查看详情</button><button v-if="orderActionLabel(o.status)" class="action" :disabled="orderUpdating===o.id" @click="advance(o)">{{orderUpdating===o.id?'处理中…':orderActionLabel(o.status)}}</button><span v-else class="action-muted">—</span></td></tr></tbody></table></div></section>
    </section>
    <section v-if="tab==='users'" class="panel"><div class="panel-toolbar"><h3>会员列表</h3><span>共 {{users.length}} 位</span></div><div class="table-wrap"><table><tr><th>ID</th><th>账号</th><th>状态</th><th>注册时间</th></tr><tr v-for="u in users" :key="u.id"><td>#{{u.id}}</td><td>{{u.username}}</td><td><i class="status completed">{{u.status==='active'?'正常':'禁用'}}</i></td><td>{{u.created_at}}</td></tr></table></div></section>
    <section v-if="tab==='payments'" class="payments-page">
      <div class="payment-toolbar panel"><div><p class="section-kicker">PAYMENT SETTINGS</p><h3>充值方式配置</h3><span>管理商城支持的收款方式与充值金额范围</span></div><button class="primary" @click="newPaymentMethod">+ 添加存款方式</button></div>
      <div v-if="paymentError" class="order-error payment-page-error">{{paymentError}} <button @click="loadPaymentMethods">重试</button></div>
      <section class="panel payment-list-panel"><div class="panel-toolbar"><div><h3>充值方式列表</h3><span class="order-count">共 {{paymentMethods.length}} 种</span></div></div><div v-if="!paymentMethods.length" class="order-empty"><div>$</div><h3>暂无充值方式</h3><p>点击“添加存款方式”配置支付宝、微信、银行卡或 USDT。</p></div><div v-else class="table-wrap payment-table"><table><thead><tr><th>ID</th><th>标识</th><th>支付名称</th><th>副名称</th><th>金额范围</th><th>线上支付</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in paymentMethods" :key="item.id"><td>#{{item.id}}</td><td><code>{{item.paytype}}</code></td><td><strong>{{item.paytypetitle}}</strong></td><td>{{item.ftitle||'—'}}</td><td>${{formatMoney(item.minmoney)}} - ${{formatMoney(item.maxmoney)}}</td><td><i :class="['payment-tag',item.isonline?'online':'manual']">{{item.isonline?'是':'否'}}</i></td><td><label class="payment-switch"><input type="checkbox" :checked="Number(item.state)===1" :aria-label="`${item.paytypetitle}状态`" @change="togglePaymentState(item)"><span></span></label></td><td class="payment-actions"><button class="action" @click="editPaymentMethod(item)">修改</button><button class="danger" @click="paymentDeleteTarget=item">删除</button></td></tr></tbody></table></div></section>
    </section>
    <section v-if="tab==='service'" class="service-workspace">
      <div class="service-queue">
        <div class="queue-head"><div><h3>客户会话</h3><small>{{openChatCount}} 个进行中<span v-if="unreadTotal"> · {{unreadTotal}} 条未读</span></small></div><span class="live-indicator"><i></i>实时</span></div>
        <div class="queue-search"><span>⌕</span><input v-model="chatSearch" placeholder="搜索客户名称"></div>
        <div class="queue-filters"><button :class="{active:chatFilter==='all'}" @click="chatFilter='all'">全部 {{chats.length}}</button><button :class="{active:chatFilter==='open'}" @click="chatFilter='open'">进行中 {{openChatCount}}</button><button :class="{active:chatFilter==='closed'}" @click="chatFilter='closed'">已结束</button></div>
        <div class="session-list"><button v-for="c in filteredChats" :key="c.id" :class="['session-card',{active:currentChat?.id===c.id,unread:Number(c.unread_count)>0}]" @click="openChat(c)"><span class="session-avatar">{{c.visitor_name.slice(0,1)}}</span><span class="session-copy"><b>{{c.visitor_name}}</b><small>{{latestPreview(c)}}</small></span><span class="session-meta"><time>{{formatChatTime(c.last_message_at)}}</time><span v-if="Number(c.unread_count)>0" class="unread-count">{{Number(c.unread_count)>99?'99+':c.unread_count}}</span><i v-else :class="c.status"></i></span></button><div v-if="!filteredChats.length" class="queue-empty">没有符合条件的会话</div></div>
      </div>
      <div v-if="currentChat" class="conversation-panel">
        <header class="conversation-head"><div class="customer-avatar">{{currentChat.visitor_name.slice(0,1)}}</div><div><h3>{{currentChat.visitor_name}}</h3><p>会话 #{{currentChat.id}} · <span :class="['conversation-status',currentChat.status]">{{currentChat.status==='open'?'服务中':'已结束'}}</span></p></div><button :class="currentChat.status==='open'?'end-session':'restore-session'" @click="closeChat(currentChat)">{{currentChat.status==='open'?'结束会话':'恢复会话'}}</button></header>
        <div v-if="serviceError" class="service-error">{{serviceError}} <button @click="openChat(currentChat)">重试</button></div>
        <div ref="chatMessagesEl" class="conversation-messages"><div class="conversation-date">本次会话</div><div v-for="m in chatMessages" :key="m.id" :class="['message-row',m.sender]"><div v-if="m.sender!=='system'" class="message-avatar">{{m.sender==='agent'?'客':currentChat.visitor_name.slice(0,1)}}</div><div v-if="m.sender==='system'" class="system-message">{{m.content}}</div><div v-else class="message-content"><span>{{m.sender==='agent'?'客服':currentChat.visitor_name}}</span><p>{{m.content}}</p><time>{{formatChatTime(m.created_at)}}</time></div></div></div>
        <div v-if="currentChat.status==='closed'" class="closed-notice">该会话已结束，恢复会话后可以继续回复。</div>
        <div class="reply-composer"><textarea v-model="reply" maxlength="2000" :disabled="currentChat.status==='closed'||replySending" @keydown.enter.exact.prevent="sendReply" placeholder="输入回复，按 Enter 发送，Shift + Enter 换行"></textarea><div><small>{{reply.length}} / 2000</small><button :disabled="currentChat.status==='closed'||replySending||!reply.trim()" @click="sendReply">{{replySending?'发送中…':'发送回复'}}</button></div></div>
      </div>
      <div v-else class="conversation-empty"><div>⌁</div><h3>选择一个客户会话</h3><p>从左侧会话列表中选择客户后开始处理咨询。</p></div>
    </section>
  </main></div>
  <div v-if="editing" class="modal-backdrop" @click.self="editing=null"><div class="modal-card product-modal"><div class="modal-head"><div><p class="modal-kicker">PRODUCT CONSOLE</p><h3>{{editing==='new'?'新增商品':'编辑商品'}}</h3></div><button class="modal-close" @click="editing=null">×</button></div><div class="editor-grid"><label>商品名称<input v-model="form.name" placeholder="请输入商品名称"></label><label>原价（选填）<input v-model="form.original_price" type="number" min="0" step="0.01" placeholder="不填则不显示原价"></label><label>优惠价<input v-model="form.price" type="number" min="0" step="0.01" placeholder="请输入销售价格"></label><label>库存数量<input v-model="form.stock" type="number" min="0" step="1" placeholder="0"></label><label>已售数量<input v-model="form.sales" type="number" min="0" step="1" placeholder="0"></label><label>商品状态<select v-model="form.status"><option value="on_sale">在售</option><option value="off_sale">已下架</option></select></label><label class="wide">商品分类<select v-model="form.category_id"><option value="">未分类</option><option v-for="c in categories" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label class="wide">商品图片<div class="image-upload"><div v-if="form.image_url" class="image-preview"><img :src="form.image_url" alt="商品图片"></div><div v-else class="image-empty">暂无图片</div><label class="upload-button">选择图片<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" @change="uploadImage"></label></div></label><label class="wide">商品描述<textarea v-model="form.description" placeholder="请输入商品描述"></textarea></label></div><div class="modal-actions"><button class="ghost" @click="editing=null">取消</button><button class="primary" @click="saveProduct">保存商品</button></div></div></div>
  <div v-if="paymentEditing" class="modal-backdrop" @click.self="paymentEditing=null"><div class="modal-card payment-modal"><div class="modal-head"><div><p class="modal-kicker">PAYMENT METHOD</p><h3>{{paymentEditing==='new'?'添加存款方式':'修改存款方式'}}</h3></div><button class="modal-close" aria-label="关闭" @click="paymentEditing=null">×</button></div><div v-if="paymentError" class="order-error payment-modal-error">{{paymentError}}</div><div class="editor-grid payment-editor">
    <label class="wide">标识<select v-model="paymentForm.paytype" :disabled="paymentEditing!=='new'" @change="changePaymentType"><option value="" disabled>请选择支付标识</option><option v-for="type in availablePaymentTypes" :key="type.value" :value="type.value" :disabled="type.disabled">{{type.label}}{{type.disabled?'（已添加）':''}}</option></select><small>标识由系统预设，创建后不可修改且不可重复。</small></label>
    <label>支付名称<input v-model="paymentForm.paytypetitle" maxlength="80" placeholder="请输入支付名称"></label><label>副名称<input v-model="paymentForm.ftitle" maxlength="80" placeholder="请输入副名称"></label>
    <label>最低金额<input v-model.number="paymentForm.minmoney" type="number" min="0" max="999999999" step="0.01"></label><label>最高金额<input v-model.number="paymentForm.maxmoney" type="number" min="0" max="999999999" step="0.01"></label>
    <div class="form-field"><span>线上支付</span><div class="choice-row"><label><input v-model.number="paymentForm.isonline" type="radio" :value="1" :disabled="paymentForm.paytype==='EpUSDT'"> 是</label><label><input v-model.number="paymentForm.isonline" type="radio" :value="0" :disabled="paymentForm.paytype==='EpUSDT'"> 否</label></div><small>{{paymentForm.paytype==='EpUSDT'?'EpUSDT 固定调用支付网关':'线上支付为第三方支付，否则为人工充值。'}}</small></div>
    <div class="form-field"><span>状态</span><div class="choice-row"><label><input v-model.number="paymentForm.state" type="radio" :value="1"> 启用</label><label><input v-model.number="paymentForm.state" type="radio" :value="0"> 禁用</label></div></div>
    <div class="payment-divider wide"><span>收款配置</span></div>
    <template v-if="['alipay','weixin'].includes(paymentForm.paytype)"><div class="form-field wide"><span>收款二维码</span><div class="payment-upload-row"><input v-model="paymentForm.configs_data.ewmurl" placeholder="二维码图片地址"><label class="upload-button">上传图片<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" @change="uploadPaymentQr"></label></div><img v-if="paymentForm.configs_data.ewmurl" class="payment-qr-preview" :src="paymentForm.configs_data.ewmurl" alt="收款二维码"></div><label>收款账号<input v-model="paymentForm.configs_data.account" maxlength="500" placeholder="收款账号/手机号"></label><label>收款人姓名<input v-model="paymentForm.configs_data.accountname" maxlength="500" placeholder="收款人姓名"></label></template>
    <template v-if="paymentForm.paytype==='linepay'"><label>银行名称<input v-model="paymentForm.configs_data.bankname" maxlength="500" placeholder="如：招商银行"></label><label>开户行<input v-model="paymentForm.configs_data.bankbranch" maxlength="500" placeholder="如：深圳分行"></label><label>银行卡号<input v-model="paymentForm.configs_data.bankcode" maxlength="500" placeholder="收款银行卡号"></label><label>收款户名<input v-model="paymentForm.configs_data.accountname" maxlength="500" placeholder="收款人真实姓名"></label></template>
    <template v-if="paymentForm.paytype==='USDT'"><label>汇率<input v-model="paymentForm.configs_data.rate" type="number" min="1" max="20" step="0.01" placeholder="1 USDT = ? USD"></label><label>TRC20 地址<input v-model="paymentForm.configs_data.trc20" maxlength="500" placeholder="TRC20 钱包地址"></label><label class="wide">ERC20 地址<input v-model="paymentForm.configs_data.erc20" maxlength="500" placeholder="ERC20 钱包地址（可选）"></label></template>
    <template v-if="paymentForm.paytype==='EpUSDT'"><label class="wide">TRC20 收款地址<input v-model="paymentForm.configs_data.trc20" maxlength="34" placeholder="请输入以 T 开头的 TRON 收款地址"><small>创建订单时作为网关收款地址，必须是有效的 TRC20 地址。</small></label></template>
    <label class="wide">备注说明<textarea v-model="paymentForm.remark" maxlength="1000" placeholder="充值说明，将显示在前端"></textarea></label>
  </div><div class="modal-actions"><button class="ghost" :disabled="paymentSaving" @click="paymentEditing=null">取消</button><button class="primary" :disabled="paymentSaving" @click="savePaymentMethod">{{paymentSaving?'保存中…':'确定'}}</button></div></div></div>
  <div v-if="deleteTarget" class="modal-backdrop" @click.self="deleteTarget=null"><div class="modal-card confirm-modal"><div class="confirm-icon">!</div><h3>确认删除商品？</h3><p>删除后“{{deleteTarget.name}}”将无法恢复，请确认是否继续。</p><div class="modal-actions"><button class="ghost" @click="deleteTarget=null">取消</button><button class="danger solid" @click="confirmDelete">确认删除</button></div></div></div>
  <div v-if="paymentDeleteTarget" class="modal-backdrop" @click.self="paymentDeleteTarget=null"><div class="modal-card confirm-modal"><div class="confirm-icon">!</div><h3>确认删除充值方式？</h3><p>删除后“{{paymentDeleteTarget.paytypetitle}}”的收款配置将无法恢复。</p><div class="modal-actions"><button class="ghost" @click="paymentDeleteTarget=null">取消</button><button class="danger solid" @click="confirmPaymentDelete">确认删除</button></div></div></div>
  <div v-if="selectedOrder" class="modal-backdrop" @click.self="selectedOrder=null"><div class="modal-card order-detail-modal"><div class="modal-head"><div><p class="modal-kicker">ORDER DETAIL</p><h3>订单详情</h3></div><button class="modal-close" aria-label="关闭订单详情" @click="selectedOrder=null">×</button></div><div v-if="orderDetailLoading" class="order-detail-loading">正在加载订单详情…</div><div v-else-if="orderDetailError" class="order-error order-detail-error">{{orderDetailError}} <button @click="openOrder(selectedOrder)">重试</button></div><template v-else><dl class="order-detail-grid"><div><dt>订单号</dt><dd>{{selectedOrder.order_no}}</dd></div><div><dt>当前状态</dt><dd><i class="status" :class="selectedOrder.status">{{orderStatusLabel(selectedOrder.status)}}</i></dd></div><div><dt>订单金额</dt><dd class="detail-amount">${{formatMoney(selectedOrder.total_amount)}}</dd></div><div><dt>支付方式</dt><dd>{{selectedOrder.payment_name||'未选择'}}（{{paymentStatusLabel(selectedOrder.payment_status)}}）</dd></div><div><dt>付款备注 / 交易号</dt><dd>{{selectedOrder.payment_reference||'未填写'}}</dd></div><div><dt>下单时间</dt><dd>{{formatDate(selectedOrder.created_at)}}</dd></div><div><dt>联系人</dt><dd>{{selectedOrder.contact_name||'在线客户'}}</dd></div><div><dt>联系电话</dt><dd>{{selectedOrder.contact_phone||'未填写'}}</dd></div><div class="wide"><dt>备注</dt><dd>{{selectedOrder.remark||'无备注'}}</dd></div></dl><section class="order-items"><h4>商品明细</h4><div v-if="!selectedOrder.items?.length" class="order-items-empty">暂无商品明细</div><div v-else class="order-items-table"><table><thead><tr><th>商品</th><th>单价</th><th>数量</th><th>小计</th></tr></thead><tbody><tr v-for="item in selectedOrder.items" :key="item.id"><td>{{item.product_name}}</td><td>${{formatMoney(item.unit_price)}}</td><td>× {{item.quantity}}</td><td>${{formatMoney(Number(item.unit_price)*Number(item.quantity))}}</td></tr></tbody></table></div></section></template><div class="modal-actions"><button class="ghost" @click="selectedOrder=null">关闭</button><button v-if="!orderDetailLoading&&!orderDetailError&&orderActionLabel(selectedOrder.status)" class="primary" :disabled="orderUpdating===selectedOrder.id" @click="advance(selectedOrder)">{{orderUpdating===selectedOrder.id?'处理中…':orderActionLabel(selectedOrder.status)}}</button></div></div></div>
  <div v-if="logoutPending" class="modal-backdrop logout-backdrop" @click.self="logoutPending=false"><div class="modal-card confirm-modal logout-modal" role="dialog" aria-modal="true" aria-labelledby="logout-title"><div class="confirm-icon logout-icon">↪</div><h3 id="logout-title">确认退出登录？</h3><p>退出后将返回管理端登录页面，需要重新输入管理员账号和密码。</p><div class="modal-actions"><button class="ghost" @click="logoutPending=false">取消</button><button class="danger solid logout-confirm" @click="logout">确认退出</button></div></div></div>
</template>

