<script setup>
import {computed,nextTick,onBeforeUnmount,onMounted,ref,watch} from 'vue';
const legacyPendingPayment=JSON.parse(localStorage.pending_payment||'null');
const storedPendingPayments=JSON.parse(localStorage.pending_payments||'[]');
const storedGuestOrderTokens=JSON.parse(localStorage.guest_order_tokens||'[]');
const initialPendingPayments=Array.isArray(storedPendingPayments)&&storedPendingPayments.length?storedPendingPayments:(legacyPendingPayment?[legacyPendingPayment]:[]);
const initialGuestOrderTokens=[...new Set([...(Array.isArray(storedGuestOrderTokens)?storedGuestOrderTokens:[]),...initialPendingPayments.map(order=>order?.guest_token).filter(Boolean)])];
const products=ref([]),cart=ref(JSON.parse(localStorage.cart||'[]')),authToken=ref(localStorage.user_token||''),showAuth=ref(false),authMode=ref('login'),authSubmitting=ref(false),captchaLoading=ref(false),captchaToken=ref(''),captchaImage=ref(''),captchaCode=ref(''),messages=ref(JSON.parse(localStorage.chat_messages||'[]')),chatToken=ref(localStorage.chat_token||''),chatReady=ref(false),chatSending=ref(false),chatError=ref(''),chatMessagesEl=ref(null),username=ref(''),password=ref(''),confirmPassword=ref(''),message=ref(''),selected=ref(null),detailQty=ref(1),orders=ref(JSON.parse(localStorage.orders||'[]')),showOrders=ref(false),activePage=ref(localStorage.active_page||'home'),previousPage=ref('home'),serviceReturn=ref(JSON.parse(localStorage.service_return||'null')),chatOpen=ref(activePage.value==='service'),notice=ref({visible:false,title:'提示',message:'',type:'info'}),paymentMethods=ref([]),showCheckout=ref(false),checkoutLoading=ref(false),checkoutSubmitting=ref(false),checkoutError=ref(''),selectedPaymentId=ref(null),pendingPaymentOrders=ref(initialPendingPayments),paymentOrder=ref(initialPendingPayments.at(-1)||null),paymentReference=ref(''),paymentConfirming=ref(false),checkoutContact=ref({name:'',phone:'',address:'',remark:''}),guestOrderTokens=ref(initialGuestOrderTokens);
if(authToken.value&&chatToken.value&&localStorage.chat_auth_state!=='user'){localStorage.removeItem('chat_token');localStorage.removeItem('chat_messages');chatToken.value='';messages.value=[]}
const categories=ref([]),selectedCategory=ref(0),isDesktop=ref(typeof window!=='undefined'&&window.innerWidth>760);
let noticeTimer;
const api=async(route,opt={})=>{opt.headers={...(opt.headers||{}),'Content-Type':'application/json',...(authToken.value?{Authorization:`Bearer ${authToken.value}`}:{})};const r=await fetch(`/api/?route=${route}`,opt);const raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw Error(r.status>=500?`客服服务暂时不可用（HTTP ${r.status}），请稍后重试`:'服务响应格式异常，请稍后重试')}if(!r.ok)throw Error(d.error||'请求失败');return d};
const cartRows=computed(()=>cart.value.map(i=>{const p=products.value.find(x=>x.id===i.product_id);return p?{...i,product:p,subtotal:Number(p.price)*i.quantity}:null}).filter(Boolean));
const total=computed(()=>cartRows.value.reduce((sum,i)=>sum+i.subtotal,0));
const eligiblePaymentMethods=computed(()=>paymentMethods.value.filter(method=>total.value>=Number(method.minmoney)&&total.value<=Number(method.maxmoney)));
const selectedPayment=computed(()=>paymentOrder.value?.payment||paymentMethods.value.find(method=>Number(method.id)===Number(selectedPaymentId.value))||null);
const paymentUsdtAmount=computed(()=>{const rate=Number(selectedPayment.value?.configs_data?.rate||0),amount=Number(paymentOrder.value?.total_amount||total.value);return rate>0?(amount/rate).toFixed(2):''});
let chatPoll,viewportListener;
onMounted(async()=>{viewportListener=()=>{isDesktop.value=window.innerWidth>760};window.addEventListener('resize',viewportListener);if(isDesktop.value&&activePage.value==='service'){activePage.value='home';chatOpen.value=false}const [productData,paymentData]=await Promise.all([api('products'),api('payment-methods').catch(()=>[])]);products.value=productData;paymentMethods.value=paymentData;const sharedProductId=new URLSearchParams(window.location.search).get('product');if(sharedProductId){const sharedProduct=products.value.find(p=>String(p.id)===String(sharedProductId));if(sharedProduct)openDetail(sharedProduct)}if(activePage.value==='service')openChat();else if(chatToken.value)refreshChat().catch(()=>{});chatPoll=setInterval(()=>{if(chatOpen.value&&chatToken.value)refreshChat().catch(e=>{if(isInvalidChatSession(e))openChat();else{chatReady.value=false;chatError.value=e.message||'客服连接失败，请重试'}})},2500)});
onMounted(()=>{api('categories').then(data=>categories.value=data).catch(()=>{})});
onBeforeUnmount(()=>{if(chatPoll)clearInterval(chatPoll);if(noticeTimer)clearTimeout(noticeTimer);if(viewportListener)window.removeEventListener('resize',viewportListener)});
watch(activePage,page=>{localStorage.active_page=page});
watch(messages,()=>nextTick(scrollChatToBottom),{deep:true});
function persist(){localStorage.cart=JSON.stringify(cart.value)}
function persistPendingPayments(){localStorage.pending_payments=JSON.stringify(pendingPaymentOrders.value);if(paymentOrder.value)localStorage.pending_payment=JSON.stringify(paymentOrder.value);else localStorage.removeItem('pending_payment')}
function persistGuestOrderTokens(){localStorage.guest_order_tokens=JSON.stringify(guestOrderTokens.value)}
async function claimGuestOrders(){if(!authToken.value||!guestOrderTokens.value.length)return;try{await api('orders/claim-guest',{method:'POST',body:JSON.stringify({guest_tokens:guestOrderTokens.value})});guestOrderTokens.value=[];persistGuestOrderTokens()}catch(e){console.warn('游客订单认领失败',e)} }
function rememberPendingPayment(order){pendingPaymentOrders.value=[...pendingPaymentOrders.value.filter(item=>Number(item.id)!==Number(order.id)),order];paymentOrder.value=order;persistPendingPayments()}
function forgetPendingPayment(orderId){pendingPaymentOrders.value=pendingPaymentOrders.value.filter(item=>Number(item.id)!==Number(orderId));paymentOrder.value=pendingPaymentOrders.value.at(-1)||null;persistPendingPayments()}
function setQty(id,value){const p=products.value.find(x=>x.id===id),item=cart.value.find(x=>x.product_id===id);if(!p||!item)return;item.quantity=Math.max(1,Math.min(Number(p.stock),Number(value)||1));persist()}
function showNotice(message,type='info',title='提示'){if(noticeTimer)clearTimeout(noticeTimer);notice.value={visible:true,title,message,type}}
function closeNotice(){notice.value.visible=false}
function add(p,qty=1){const item=cart.value.find(i=>i.product_id===p.id);const next=(item?.quantity||0)+qty;if(next>p.stock){showNotice(`库存不足，最多可购买 ${p.stock} 件`,'warning','库存提醒');return false}if(item)item.quantity=next;else cart.value.push({product_id:p.id,quantity:qty});persist();return true}
function remove(id){cart.value=cart.value.filter(i=>i.product_id!==id);persist()}
function openDetail(p){selected.value=p;detailQty.value=1}
function openDetailChat(){if(selected.value){serviceReturn.value={page:activePage.value,product:selected.value,qty:detailQty.value};localStorage.service_return=JSON.stringify(serviceReturn.value);selected.value=null}navService(true)}
function buyNow(){if(!selected.value)return;const product=selected.value;if(!add(product,detailQty.value))return;selected.value=null;openCheckout()}
async function shareProduct(){const product=selected.value;if(!product)return;const shareUrl=new URL(window.location.href);shareUrl.searchParams.set('product',product.id);const shareData={title:product.name,text:`${product.name} ¥${product.price}`,url:shareUrl.toString()};try{if(typeof navigator.share==='function'){await navigator.share(shareData);return}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(shareData.url);showNotice('商品链接已复制到剪贴板','success','分享成功');return}const textarea=document.createElement('textarea');textarea.value=shareData.url;textarea.setAttribute('readonly','');textarea.style.position='fixed';textarea.style.opacity='0';document.body.appendChild(textarea);textarea.select();const copied=document.execCommand('copy');textarea.remove();if(copied){showNotice('商品链接已复制到剪贴板','success','分享成功');return}throw Error('clipboard unavailable')}catch(error){if(error?.name==='AbortError')return;showNotice('分享失败，请稍后重试','error','分享失败')}}
function showAuthPanel(){showAuth.value=true;if(authMode.value==='register'&&!captchaImage.value)loadCaptcha()}
function setAuthMode(mode){authMode.value=mode;confirmPassword.value='';if(mode==='register')loadCaptcha();else captchaCode.value=''}
async function loadCaptcha(){captchaLoading.value=true;captchaToken.value='';captchaImage.value='';captchaCode.value='';try{const d=await api('auth/captcha');captchaToken.value=d.captcha_token;captchaImage.value=d.captcha_image}catch(e){showNotice(e.message||'验证码加载失败，请重试','error','验证码加载失败')}finally{captchaLoading.value=false}}
async function auth(kind=authMode.value){if(authSubmitting.value)return;authSubmitting.value=true;try{const payload={username:username.value,password:password.value};if(kind==='register'){if(password.value!==confirmPassword.value){showNotice('两次输入的密码不一致','warning','注册信息不完整');return}if(!captchaToken.value||!captchaCode.value.trim()){showNotice('请输入验证码','warning','注册信息不完整');return}payload.confirm_password=confirmPassword.value;payload.captcha_token=captchaToken.value;payload.captcha_code=captchaCode.value}const d=await api(`auth/${kind}`,{method:'POST',body:JSON.stringify(payload)});authToken.value=d.token;localStorage.user_token=d.token;await claimGuestOrders();resetChatSession();showAuth.value=false;if(activePage.value==='mine')await loadOrders();showNotice(kind==='register'?'注册成功，欢迎加入闪购商城':'欢迎回来，账号已登录','success',kind==='register'?'注册成功':'登录成功')}catch(e){if(kind==='register')loadCaptcha().catch(()=>{});showNotice(e.message,'error','操作失败')}finally{authSubmitting.value=false}}
async function loadPaymentMethods(){paymentMethods.value=await api('payment-methods')}
async function openCheckout(){if(!cartRows.value.length){if(paymentOrder.value)resumePayment();else showNotice('请先加入商品','warning','购物车为空');return}paymentOrder.value=null;showCheckout.value=true;checkoutLoading.value=true;checkoutError.value='';paymentReference.value='';try{await loadPaymentMethods();const first=eligiblePaymentMethods.value[0];selectedPaymentId.value=first?.id??null;if(!paymentMethods.value.length)checkoutError.value='暂无可用支付方式，请联系客服';else if(!first)checkoutError.value='订单金额不符合当前支付方式的限额，请调整商品数量或联系客服'}catch(e){checkoutError.value=e.message||'支付方式加载失败'}finally{checkoutLoading.value=false}}
function closeCheckout(){if(checkoutSubmitting.value||paymentConfirming.value)return;showCheckout.value=false;checkoutError.value='';if(!paymentOrder.value)paymentOrder.value=pendingPaymentOrders.value.at(-1)||null}
async function createPaymentOrder(){if(!selectedPayment.value||checkoutSubmitting.value)return;checkoutSubmitting.value=true;checkoutError.value='';try{const d=await api('orders',{method:'POST',body:JSON.stringify({items:cartRows.value.map(i=>({product_id:i.product_id,quantity:i.quantity})),payment_method_id:selectedPayment.value.id,contact_name:checkoutContact.value.name.trim()||'在线客户',contact_phone:checkoutContact.value.phone.trim(),shipping_address:checkoutContact.value.address.trim(),remark:checkoutContact.value.remark.trim()})});rememberPendingPayment(d);if(d.guest_token&&!guestOrderTokens.value.includes(d.guest_token)){guestOrderTokens.value=[...guestOrderTokens.value,d.guest_token];persistGuestOrderTokens()}cart.value=[];persist();products.value=await api('products')}catch(e){checkoutError.value=e.message||'订单创建失败';try{await loadPaymentMethods()}catch{}}finally{checkoutSubmitting.value=false}}
function resumePayment(){const order=paymentOrder.value||pendingPaymentOrders.value.at(-1);if(!order)return;paymentOrder.value=order;paymentReference.value='';checkoutError.value='';showCheckout.value=true;persistPendingPayments()}
function hasPaymentDetails(method){return Object.values(method?.configs_data||{}).some(value=>String(value||'').trim()!=='')}
function paymentStatusText(status){return ({unpaid:'待付款',submitted:'待确认',confirmed:'已确认',failed:'已关闭'})[status]||'待付款'}
function paymentMethodHint(method){return method.ftitle||`限额 ¥${Number(method.minmoney).toFixed(2)} - ¥${Number(method.maxmoney).toFixed(2)}`}
async function submitPayment(){if(!paymentOrder.value||paymentConfirming.value)return;paymentConfirming.value=true;checkoutError.value='';try{await api(`orders/${paymentOrder.value.id}/payment-submitted`,{method:'POST',body:JSON.stringify({guest_token:paymentOrder.value.guest_token,payment_reference:paymentReference.value.trim()})});const paidOrderId=paymentOrder.value.id,orderNo=paymentOrder.value.order_no;showCheckout.value=false;forgetPendingPayment(paidOrderId);showNotice(`订单 ${orderNo} 已提交付款，等待后台确认`,'success','付款已提交')}catch(e){checkoutError.value=e.message||'付款状态提交失败'}finally{paymentConfirming.value=false}}
async function loadOrders(){activePage.value='mine';showOrders.value=true;try{orders.value=await api('orders');localStorage.orders=JSON.stringify(orders.value)}catch(e){showNotice('请先登录后查看订单','warning','需要登录')}}
function isInvalidChatSession(error){return ['会话不存在','会话已关闭'].includes(error?.message)}
function resetChatSession(){chatToken.value='';messages.value=[];chatReady.value=false;localStorage.removeItem('chat_token');localStorage.removeItem('chat_messages');localStorage.removeItem('chat_auth_state')}
async function createChatSession(){const d=await api('chat/session',{method:'POST'});chatToken.value=d.token;localStorage.chat_token=chatToken.value;localStorage.chat_auth_state=authToken.value?'user':'guest'}
function scrollChatToBottom(){const el=chatMessagesEl.value;if(el)el.scrollTop=el.scrollHeight}
async function openChat(){chatOpen.value=true;chatError.value='';chatReady.value=false;try{if(!chatToken.value)await createChatSession();await refreshChat();chatReady.value=true}catch(e){if(isInvalidChatSession(e)){resetChatSession();try{await createChatSession();await refreshChat();chatReady.value=true;return}catch(recoveryError){e=recoveryError}}chatReady.value=false;chatError.value=e.message||'客服连接失败，请重试'}}
async function refreshChat(){if(!chatToken.value)return;try{const data=await api(`chat/messages/${chatToken.value}`);messages.value=data;localStorage.chat_messages=JSON.stringify(data);chatReady.value=true;chatError.value=''}catch(e){if(isInvalidChatSession(e))resetChatSession();throw e}}
async function postMessage(content){try{await api(`chat/messages/${chatToken.value}`,{method:'POST',body:JSON.stringify({content})})}catch(e){if(!isInvalidChatSession(e))throw e;resetChatSession();await createChatSession();await refreshChat();await api(`chat/messages/${chatToken.value}`,{method:'POST',body:JSON.stringify({content})})}await refreshChat()}
async function deliverMessage(content,restoreDraft=false){content=content.trim();if(!content||chatSending.value)return;chatSending.value=true;chatError.value='';if(restoreDraft)message.value='';try{if(!chatToken.value||!chatReady.value)await openChat();if(!chatToken.value||!chatReady.value)throw Error(chatError.value||'客服暂时无法连接');await postMessage(content)}catch(e){if(restoreDraft)message.value=content;chatError.value=e.message||'消息发送失败';chatReady.value=false}finally{chatSending.value=false}}
async function send(){await deliverMessage(message.value,true)}
async function sendQuick(content){await deliverMessage(content)}
function navHome(){activePage.value='home';chatOpen.value=false;showOrders.value=false;window.scrollTo({top:0,behavior:'smooth'})}
async function navCategory(id=0){selectedCategory.value=id;activePage.value='home';chatOpen.value=false;showOrders.value=false;products.value=await api(id?`products&category_id=${id}`:'products');window.scrollTo({top:0,behavior:'smooth'})}
function navCart(){activePage.value='cart';chatOpen.value=false;showOrders.value=false;window.scrollTo({top:0,behavior:'smooth'})}
function navService(fromDetail=false){if(isDesktop.value){if(!fromDetail){serviceReturn.value=null;localStorage.removeItem('service_return')}chatOpen.value=true;openChat();return}if(activePage.value!=='service'){previousPage.value=activePage.value;if(!fromDetail){serviceReturn.value=null;localStorage.removeItem('service_return')}}activePage.value='service';openChat()}
function closeDesktopChat(){chatOpen.value=false;chatError.value=''}
function leaveService(){const returnState=serviceReturn.value;serviceReturn.value=null;localStorage.removeItem('service_return');activePage.value=returnState?.page||previousPage.value||'home';if(returnState?.product){selected.value=returnState.product;detailQty.value=returnState.qty||1}chatOpen.value=false;showOrders.value=activePage.value==='mine';nextTick(()=>window.scrollTo({top:0}))}
function navMine(){activePage.value='mine';showOrders.value=true;chatOpen.value=false;loadOrders()}
</script>
<template>
<header class="desktop-header"><strong class="brand-lockup"><img src="/brand-mark.png" alt="" aria-hidden="true"><span>闪购商城</span></strong><nav><button @click="showAuthPanel">登录 / 注册</button><button @click="loadOrders">我的订单</button><button v-if="paymentOrder" class="pending-payment-link" @click="resumePayment">继续支付</button><span>购物车 {{cartRows.length}} 件 · ¥{{total.toFixed(2)}}</span></nav></header>
<section v-if="activePage==='home'" class="hero"><main><div class="hero-brand"><img src="/brand-mark.png" alt="" aria-hidden="true"><strong>闪购商城</strong></div><p>精选商品，快速下单，游客也能咨询客服。</p></main></section>
<div v-if="activePage==='home'" class="category-nav"><button :class="{active:!selectedCategory}" @click="navCategory()">全部</button><button v-for="c in categories" :key="c.id" :class="{active:selectedCategory===c.id}" @click="navCategory(c.id)">{{c.name}}</button></div>
<main><section v-if="activePage==='home'"><h2>精选商品</h2><div class="grid"><article v-for="p in products" :key="p.id"><div class="product-image product-link" @click="openDetail(p)"><img v-if="p.image_url" :src="p.image_url" :alt="p.name"><span v-else>{{p.name.slice(0,1)}}</span></div><h3 class="product-link" @click="openDetail(p)">{{p.name}}</h3><p>{{p.description}}</p><b>¥ {{p.price}}</b><del v-if="p.original_price">¥ {{p.original_price}}</del><small>库存 {{p.stock}}</small><div><button class="buy-button" @click="openDetail(p)">立即购买</button><button class="cart-button" @click="add(p)">加入购物车</button></div></article></div></section>
<section id="cart" v-if="activePage==='cart'" class="cart"><h2>购物车</h2><div v-if="!cartRows.length">购物车为空</div><div v-for="i in cartRows" :key="i.product_id" class="cart-row"><span>{{i.product.name}}</span><span>¥{{Number(i.product.price).toFixed(2)}} × <button @click="setQty(i.product_id,i.quantity-1)">−</button><input type="number" :value="i.quantity" @change="setQty(i.product_id,$event.target.value)"><button @click="setQty(i.product_id,i.quantity+1)">＋</button></span><strong>¥{{i.subtotal.toFixed(2)}}</strong><button @click="remove(i.product_id)">删除</button></div><div class="cart-total">合计：<b>¥{{total.toFixed(2)}}</b><button @click="openCheckout">立即支付</button></div></section>
<section v-if="activePage==='mine'" class="cart"><h2>我的订单</h2><button v-if="!authToken" @click="showAuthPanel">登录 / 注册</button><div v-if="authToken&&!orders.length">暂无订单</div><div v-for="o in orders" :key="o.id" class="user-order-row"><div><b>{{o.order_no}}</b><small>{{o.payment_name||'未选择支付方式'}}</small></div><strong>¥{{Number(o.total_amount).toFixed(2)}}</strong><span>{{paymentStatusText(o.payment_status)}}</span></div></section>
<section v-if="activePage==='service'||(isDesktop&&chatOpen)" class="service-page" :class="{ 'desktop-service-modal': isDesktop&&activePage!=='service' }" @click.self="closeDesktopChat">
  <div class="service-intro"><div><span class="service-kicker">CUSTOMER CARE</span><h1>在线客服</h1><p>遇到问题？请发送消息联系我们</p></div></div>
  <div class="service-layout">
    <aside class="service-sidebar"><h3>常见问题</h3><button v-for="q in ['如何查看订单状态？','支付后多久发货？','如何申请退款？','商品可以开发票吗？']" :key="q" :disabled="chatSending" @click="sendQuick(q)">{{q}}<span>›</span></button><div class="sidebar-tip"><span>✦</span><div><b>需要人工帮助？</b><small>点击问题或直接发送消息</small></div></div></aside>
    <div class="service-chat-panel">
      <div class="chat-panel-head"><button class="mobile-chat-back" aria-label="返回" @click="leaveService">‹</button><div class="agent-avatar">客</div><div><b>闪购商城客服</b></div><button class="desktop-chat-close" aria-label="关闭客服弹窗" @click="closeDesktopChat">×</button></div>
      <div ref="chatMessagesEl" class="messages service-messages"><div class="chat-date">今天</div><div v-if="chatError" class="chat-error">{{chatError}} <button @click="openChat">重新连接</button></div><div class="system-note">欢迎来到闪购商城，很高兴为你服务</div><p v-for="m in messages" :class="m.sender" :key="m.id">{{m.content}}<small v-if="m.created_at">{{new Date(m.created_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}}</small></p></div>
      <div class="quick-replies"><button v-for="q in ['查订单','退款政策','配送时效']" :key="q" :disabled="!chatReady||chatSending" @click="sendQuick(q)">{{q}}</button></div>
      <div class="chat-compose"><input v-model="message" :disabled="!chatReady||chatSending" @keyup.enter="send" placeholder="请输入消息"><button class="send-btn" :disabled="!chatReady||chatSending||!message.trim()" @click="send">{{chatSending?'发送中':'发送'}}</button></div>
      <small class="chat-security">消息仅用于本次客服沟通</small>
    </div>
  </div>
</section></main>
<button v-if="activePage==='home'" class="chat-fab" @click="navService">在线客服</button>
<button v-if="paymentOrder&&!showCheckout&&activePage!=='service'" class="resume-payment-fab" @click="resumePayment">继续支付 ¥{{Number(paymentOrder.total_amount).toFixed(2)}}</button>
<div v-if="selected" class="product-detail-screen"><div class="detail-topbar"><button @click="selected=null" aria-label="返回">‹</button><span>商品详情</span><button @click="shareProduct" aria-label="分享">↗</button></div><div class="detail-gallery"><div class="product-image large"><img v-if="selected.image_url" :src="selected.image_url" :alt="selected.name"><span v-else>{{selected.name.slice(0,1)}}</span></div><div class="gallery-count">1 / 1</div></div><div class="detail-content"><div class="detail-price"><b>¥{{selected.price}}</b><del v-if="selected.original_price">¥{{selected.original_price}}</del><span>已售 {{selected.sales??0}}</span></div><h2>{{selected.name}}</h2><p class="detail-description">{{selected.description}}</p><div class="detail-tags"><span>正品保障</span><span>极速发货</span><span>售后无忧</span></div><div class="detail-row"><span>配送</span><b>默认快递 · 预计 1-3 天送达</b><i>›</i></div><div class="detail-row"><span>服务</span><b>支持在线客服 · 订单保障</b><i>›</i></div><div class="detail-quantity"><span>购买数量</span><div><button @click="detailQty=Math.max(1,detailQty-1)">−</button><input type="number" v-model.number="detailQty" :min="1" :max="selected.stock"><button @click="detailQty=Math.min(selected.stock,detailQty+1)">＋</button></div></div></div><div class="detail-actions"><button class="detail-service" @click="openDetailChat" aria-label="联系客服"><svg class="detail-service-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 13v-1a8 8 0 0 1 16 0v1"/><path d="M4 13a2 2 0 0 0 2 2h1v-5H6a2 2 0 0 0-2 2Zm16 0a2 2 0 0 1-2 2h-1v-5h1a2 2 0 0 1 2 2Z"/><path d="M15 19h-2a2 2 0 0 1-2-2"/></svg><small>客服</small></button><button class="detail-cart" @click="add(selected,detailQty);selected=null">加入购物车</button><button class="detail-buy" @click="buyNow">立即支付</button></div></div>
<div v-if="showCheckout" class="checkout-overlay" @click.self="closeCheckout"><div class="checkout-card" role="dialog" aria-modal="true" aria-labelledby="checkout-title"><header class="checkout-head"><div><small>{{paymentOrder?'PAYMENT':'CHECKOUT'}}</small><h2 id="checkout-title">{{paymentOrder?'完成付款':'确认订单'}}</h2></div><button aria-label="关闭支付" @click="closeCheckout">×</button></header>
  <div v-if="checkoutLoading" class="checkout-loading">正在加载支付方式…</div>
  <template v-else-if="!paymentOrder"><section class="checkout-summary"><div v-for="item in cartRows" :key="item.product_id"><span>{{item.product.name}} × {{item.quantity}}</span><b>¥{{item.subtotal.toFixed(2)}}</b></div><p><span>应付金额</span><strong>¥{{total.toFixed(2)}}</strong></p></section><section class="checkout-contact"><h3>联系信息</h3><div><input v-model="checkoutContact.name" maxlength="80" placeholder="联系人"><input v-model="checkoutContact.phone" maxlength="40" placeholder="联系电话"></div><input v-model="checkoutContact.address" maxlength="300" placeholder="寄送地址"><input v-model="checkoutContact.remark" maxlength="500" placeholder="订单备注（选填）"></section><section class="checkout-methods"><h3>选择支付方式</h3><div v-if="eligiblePaymentMethods.length" class="payment-method-options"><button v-for="method in eligiblePaymentMethods" :key="method.id" :class="{active:Number(selectedPaymentId)===Number(method.id)}" @click="selectedPaymentId=method.id"><i>{{method.paytype==='alipay'?'支':method.paytype==='weixin'?'微':method.paytype==='linepay'?'卡':'₮'}}</i><span><b>{{method.paytypetitle}}</b><small>{{paymentMethodHint(method)}}</small></span><em>✓</em></button></div><p v-if="selectedPayment?.remark" class="payment-remark">{{selectedPayment.remark}}</p></section><div v-if="checkoutError" class="checkout-error">{{checkoutError}}</div><footer class="checkout-actions"><button class="checkout-cancel" @click="closeCheckout">取消</button><button class="checkout-submit" :disabled="!selectedPayment||checkoutSubmitting" @click="createPaymentOrder">{{checkoutSubmitting?'正在创建订单…':'立即支付'}}</button></footer></template>
  <template v-else><section class="payment-order-summary"><span class="payment-pending">待付款</span><small>订单号 {{paymentOrder.order_no}}</small><strong>¥{{Number(paymentOrder.total_amount).toFixed(2)}}</strong><p>请使用 {{selectedPayment.paytypetitle}} 完成付款</p></section><section class="payment-instructions"><img v-if="selectedPayment.configs_data.ewmurl" :src="selectedPayment.configs_data.ewmurl" alt="收款二维码" class="checkout-qr"><div v-if="paymentUsdtAmount" class="usdt-amount"><span>需支付</span><b>{{paymentUsdtAmount}} USDT</b><small>汇率：1 USDT = ¥{{selectedPayment.configs_data.rate}}</small></div><dl v-if="hasPaymentDetails(selectedPayment)"><div v-if="selectedPayment.configs_data.account"><dt>收款账号</dt><dd>{{selectedPayment.configs_data.account}}</dd></div><div v-if="selectedPayment.configs_data.accountname"><dt>收款人</dt><dd>{{selectedPayment.configs_data.accountname}}</dd></div><div v-if="selectedPayment.configs_data.bankname"><dt>银行名称</dt><dd>{{selectedPayment.configs_data.bankname}}</dd></div><div v-if="selectedPayment.configs_data.bankbranch"><dt>开户行</dt><dd>{{selectedPayment.configs_data.bankbranch}}</dd></div><div v-if="selectedPayment.configs_data.bankcode"><dt>银行卡号</dt><dd>{{selectedPayment.configs_data.bankcode}}</dd></div><div v-if="selectedPayment.configs_data.trc20"><dt>TRC20 地址</dt><dd>{{selectedPayment.configs_data.trc20}}</dd></div><div v-if="selectedPayment.configs_data.erc20"><dt>ERC20 地址</dt><dd>{{selectedPayment.configs_data.erc20}}</dd></div></dl><p v-else class="payment-config-missing">收款信息尚未配置完整，请联系在线客服。</p><p v-if="selectedPayment.remark" class="payment-remark">{{selectedPayment.remark}}</p></section><label class="payment-reference">付款备注 / 交易号（选填）<input v-model="paymentReference" maxlength="120" placeholder="便于后台快速核对"></label><div v-if="checkoutError" class="checkout-error">{{checkoutError}}</div><footer class="checkout-actions"><button class="checkout-cancel" @click="closeCheckout">稍后支付</button><button class="checkout-submit" :disabled="paymentConfirming" @click="submitPayment">{{paymentConfirming?'正在提交…':'我已完成付款'}}</button></footer></template>
</div></div>
<div v-if="showAuth" class="modal"><div class="modal-card auth-card"><button class="close" @click="showAuth=false">×</button><h2>{{authMode==='login'?'登录':'注册'}}</h2><div class="auth-tabs" role="tablist"><button :class="{active:authMode==='login'}" @click="setAuthMode('login')">登录</button><button :class="{active:authMode==='register'}" @click="setAuthMode('register')">注册</button></div><input v-model="username" placeholder="用户名" autocomplete="username"><input v-model="password" type="password" placeholder="密码" :autocomplete="authMode==='register'?'new-password':'current-password'"><input v-if="authMode==='register'" v-model="confirmPassword" type="password" placeholder="确认密码" autocomplete="new-password" @keyup.enter="auth('register')"><div v-if="authMode==='register'" class="captcha-field"><input v-model="captchaCode" placeholder="请输入验证码" maxlength="8" autocomplete="off" @keyup.enter="auth('register')"><button type="button" class="captcha-image-button" :disabled="captchaLoading" @click="loadCaptcha" :aria-label="captchaLoading?'验证码加载中':'刷新验证码'"><img v-if="captchaImage&&!captchaLoading" :src="captchaImage" alt="验证码"><span v-else>加载中…</span></button></div><button class="auth-submit" :disabled="authSubmitting" @click="auth()">{{authSubmitting?'提交中…':authMode==='login'?'登录':'注册'}}</button></div></div>
<div v-if="notice.visible" class="notice-modal" role="presentation" tabindex="-1" @click.self="closeNotice" @keydown.esc="closeNotice"><div class="notice-card" :class="`notice-${notice.type}`" role="dialog" aria-modal="true" aria-labelledby="notice-title" aria-describedby="notice-message"><div class="notice-icon" aria-hidden="true">{{notice.type==='success'?'✓':notice.type==='warning'?'!':notice.type==='error'?'×':'i'}}</div><div class="notice-copy"><h2 id="notice-title">{{notice.title}}</h2><p id="notice-message">{{notice.message}}</p></div><button class="notice-close" aria-label="关闭提示" @click="closeNotice">×</button><button class="notice-action" @click="closeNotice">知道了</button></div></div>
<div v-if="chatOpen && activePage!=='service'" class="chat service-chat"><b>在线客服 <button @click="chatOpen=false;activePage='home'">×</button></b><div class="messages"><p v-for="m in messages" :class="m.sender" :key="m.id">{{m.content}}</p></div><input v-model="message" @keyup.enter="send" placeholder="请输入问题"><button @click="send">发送</button></div>
<nav v-if="activePage!=='service'" class="mobile-bottom-nav" aria-label="移动端导航"><button :class="{active:activePage==='home'}" @click="navHome"><span>⌂</span><small>首页</small></button><button :class="{active:activePage==='cart'}" @click="navCart"><span>🛒<i v-if="cartRows.length">{{cartRows.length}}</i></span><small>购物车</small></button><button @click="navService"><span>◌</span><small>客服</small></button><button :class="{active:activePage==='mine'}" @click="navMine"><span>♙</span><small>我的</small></button></nav>
</template>

