<script setup>
import {computed,nextTick,onBeforeUnmount,onMounted,ref,watch} from 'vue';
const products=ref([]),cart=ref(JSON.parse(localStorage.cart||'[]')),authToken=ref(localStorage.user_token||''),showAuth=ref(false),authMode=ref('login'),authSubmitting=ref(false),captchaLoading=ref(false),captchaToken=ref(''),captchaImage=ref(''),captchaCode=ref(''),messages=ref(JSON.parse(localStorage.chat_messages||'[]')),chatToken=ref(localStorage.chat_token||''),chatReady=ref(false),chatSending=ref(false),chatError=ref(''),chatMessagesEl=ref(null),username=ref(''),password=ref(''),message=ref(''),selected=ref(null),detailQty=ref(1),orders=ref(JSON.parse(localStorage.orders||'[]')),showOrders=ref(false),activePage=ref(localStorage.active_page||'home'),previousPage=ref('home'),serviceReturn=ref(JSON.parse(localStorage.service_return||'null')),chatOpen=ref(activePage.value==='service'),notice=ref({visible:false,title:'提示',message:'',type:'info'});
let noticeTimer;
const api=async(route,opt={})=>{opt.headers={...(opt.headers||{}),'Content-Type':'application/json',...(authToken.value?{Authorization:`Bearer ${authToken.value}`}:{})};const r=await fetch(`/api/?route=${route}`,opt);const raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw Error(r.status>=500?`客服服务暂时不可用（HTTP ${r.status}），请稍后重试`:'服务响应格式异常，请稍后重试')}if(!r.ok)throw Error(d.error||'请求失败');return d};
const cartRows=computed(()=>cart.value.map(i=>{const p=products.value.find(x=>x.id===i.product_id);return p?{...i,product:p,subtotal:Number(p.price)*i.quantity}:null}).filter(Boolean));
const total=computed(()=>cartRows.value.reduce((sum,i)=>sum+i.subtotal,0));
let chatPoll;
onMounted(async()=>{products.value=await api('products');const sharedProductId=new URLSearchParams(window.location.search).get('product');if(sharedProductId){const sharedProduct=products.value.find(p=>String(p.id)===String(sharedProductId));if(sharedProduct)openDetail(sharedProduct)}if(activePage.value==='service')openChat();else if(chatToken.value)refreshChat().catch(()=>{});chatPoll=setInterval(()=>{if(chatOpen.value&&chatToken.value)refreshChat().catch(e=>{if(isInvalidChatSession(e))openChat();else{chatReady.value=false;chatError.value=e.message||'客服连接失败，请重试'}})},2500)});
onBeforeUnmount(()=>{if(chatPoll)clearInterval(chatPoll);if(noticeTimer)clearTimeout(noticeTimer)});
watch(activePage,page=>{localStorage.active_page=page});
watch(messages,()=>nextTick(scrollChatToBottom),{deep:true});
function persist(){localStorage.cart=JSON.stringify(cart.value)}
function setQty(id,value){const p=products.value.find(x=>x.id===id),item=cart.value.find(x=>x.product_id===id);if(!p||!item)return;item.quantity=Math.max(1,Math.min(Number(p.stock),Number(value)||1));persist()}
function showNotice(message,type='info',title='提示'){if(noticeTimer)clearTimeout(noticeTimer);notice.value={visible:true,title,message,type}}
function closeNotice(){notice.value.visible=false}
function add(p,qty=1){const item=cart.value.find(i=>i.product_id===p.id);const next=(item?.quantity||0)+qty;if(next>p.stock)return showNotice(`库存不足，最多可购买 ${p.stock} 件`,'warning','库存提醒');if(item)item.quantity=next;else cart.value.push({product_id:p.id,quantity:qty});persist()}
function remove(id){cart.value=cart.value.filter(i=>i.product_id!==id);persist()}
function openDetail(p){selected.value=p;detailQty.value=1}
function openDetailChat(){if(selected.value){serviceReturn.value={page:activePage.value,product:selected.value,qty:detailQty.value};localStorage.service_return=JSON.stringify(serviceReturn.value);selected.value=null}navService(true)}
function buyNow(){if(selected.value){add(selected.value,detailQty.value);selected.value=null;document.querySelector('#cart')?.scrollIntoView({behavior:'smooth'})}}
async function shareProduct(){const product=selected.value;if(!product)return;const shareUrl=new URL(window.location.href);shareUrl.searchParams.set('product',product.id);const shareData={title:product.name,text:`${product.name} ¥${product.price}`,url:shareUrl.toString()};try{if(typeof navigator.share==='function'){await navigator.share(shareData);return}if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(shareData.url);showNotice('商品链接已复制到剪贴板','success','分享成功');return}const textarea=document.createElement('textarea');textarea.value=shareData.url;textarea.setAttribute('readonly','');textarea.style.position='fixed';textarea.style.opacity='0';document.body.appendChild(textarea);textarea.select();const copied=document.execCommand('copy');textarea.remove();if(copied){showNotice('商品链接已复制到剪贴板','success','分享成功');return}throw Error('clipboard unavailable')}catch(error){if(error?.name==='AbortError')return;showNotice('分享失败，请稍后重试','error','分享失败')}}
function showAuthPanel(){showAuth.value=true;if(authMode.value==='register'&&!captchaImage.value)loadCaptcha()}
function setAuthMode(mode){authMode.value=mode;if(mode==='register')loadCaptcha();else captchaCode.value=''}
async function loadCaptcha(){captchaLoading.value=true;captchaToken.value='';captchaImage.value='';captchaCode.value='';try{const d=await api('auth/captcha');captchaToken.value=d.captcha_token;captchaImage.value=d.captcha_image}catch(e){showNotice(e.message||'验证码加载失败，请重试','error','验证码加载失败')}finally{captchaLoading.value=false}}
async function auth(kind=authMode.value){if(authSubmitting.value)return;authSubmitting.value=true;try{const payload={username:username.value,password:password.value};if(kind==='register'){if(!captchaToken.value||!captchaCode.value.trim()){showNotice('请输入验证码','warning','注册信息不完整');return}payload.captcha_token=captchaToken.value;payload.captcha_code=captchaCode.value}const d=await api(`auth/${kind}`,{method:'POST',body:JSON.stringify(payload)});authToken.value=d.token;localStorage.user_token=d.token;showAuth.value=false;showNotice(kind==='register'?'注册成功，欢迎加入轻量商城':'欢迎回来，账号已登录','success',kind==='register'?'注册成功':'登录成功')}catch(e){if(kind==='register')loadCaptcha().catch(()=>{});showNotice(e.message,'error','操作失败')}finally{authSubmitting.value=false}}
async function checkout(){if(!cartRows.value.length)return showNotice('请先加入商品','warning','购物车为空');try{const d=await api('orders',{method:'POST',body:JSON.stringify({items:cartRows.value.map(i=>({product_id:i.product_id,quantity:i.quantity})),contact_name:'在线客户'})});showNotice(`订单 ${d.order_no} 已创建，总额 ¥${d.total_amount}`,'success','下单成功');cart.value=[];persist();products.value=await api('products')}catch(e){showNotice(e.message,'error','下单失败')}}
async function loadOrders(){activePage.value='mine';showOrders.value=true;try{orders.value=await api('orders');localStorage.orders=JSON.stringify(orders.value)}catch(e){showNotice('请先登录后查看订单','warning','需要登录')}}
function isInvalidChatSession(error){return ['会话不存在','会话已关闭'].includes(error?.message)}
function resetChatSession(){chatToken.value='';messages.value=[];chatReady.value=false;localStorage.removeItem('chat_token');localStorage.removeItem('chat_messages')}
async function createChatSession(){const d=await api('chat/session',{method:'POST',body:JSON.stringify({visitor_name:authToken.value?'会员用户':'游客'})});chatToken.value=d.token;localStorage.chat_token=chatToken.value}
function scrollChatToBottom(){const el=chatMessagesEl.value;if(el)el.scrollTop=el.scrollHeight}
async function openChat(){chatOpen.value=true;chatError.value='';chatReady.value=false;try{if(!chatToken.value)await createChatSession();await refreshChat();chatReady.value=true}catch(e){if(isInvalidChatSession(e)){resetChatSession();try{await createChatSession();await refreshChat();chatReady.value=true;return}catch(recoveryError){e=recoveryError}}chatReady.value=false;chatError.value=e.message||'客服连接失败，请重试'}}
async function refreshChat(){if(!chatToken.value)return;try{const data=await api(`chat/messages/${chatToken.value}`);messages.value=data;localStorage.chat_messages=JSON.stringify(data);chatReady.value=true;chatError.value=''}catch(e){if(isInvalidChatSession(e))resetChatSession();throw e}}
async function postMessage(content){try{await api(`chat/messages/${chatToken.value}`,{method:'POST',body:JSON.stringify({content})})}catch(e){if(!isInvalidChatSession(e))throw e;resetChatSession();await createChatSession();await refreshChat();await api(`chat/messages/${chatToken.value}`,{method:'POST',body:JSON.stringify({content})})}await refreshChat()}
async function deliverMessage(content,restoreDraft=false){content=content.trim();if(!content||chatSending.value)return;chatSending.value=true;chatError.value='';if(restoreDraft)message.value='';try{if(!chatToken.value||!chatReady.value)await openChat();if(!chatToken.value||!chatReady.value)throw Error(chatError.value||'客服暂时无法连接');await postMessage(content)}catch(e){if(restoreDraft)message.value=content;chatError.value=e.message||'消息发送失败';chatReady.value=false}finally{chatSending.value=false}}
async function send(){await deliverMessage(message.value,true)}
async function sendQuick(content){await deliverMessage(content)}
function navHome(){activePage.value='home';chatOpen.value=false;showOrders.value=false;window.scrollTo({top:0,behavior:'smooth'})}
function navCart(){activePage.value='cart';chatOpen.value=false;showOrders.value=false;window.scrollTo({top:0,behavior:'smooth'})}
function navService(fromDetail=false){if(activePage.value!=='service'){previousPage.value=activePage.value;if(!fromDetail){serviceReturn.value=null;localStorage.removeItem('service_return')}}activePage.value='service';openChat()}
function leaveService(){const returnState=serviceReturn.value;serviceReturn.value=null;localStorage.removeItem('service_return');activePage.value=returnState?.page||previousPage.value||'home';if(returnState?.product){selected.value=returnState.product;detailQty.value=returnState.qty||1}chatOpen.value=false;showOrders.value=activePage.value==='mine';nextTick(()=>window.scrollTo({top:0}))}
function navMine(){activePage.value='mine';showOrders.value=true;chatOpen.value=false;loadOrders()}
</script>
<template>
<header class="desktop-header"><strong>轻量商城</strong><nav><button @click="showAuthPanel">登录 / 注册</button><button @click="loadOrders">我的订单</button><span>购物车 {{cartRows.length}} 件 · ¥{{total.toFixed(2)}}</span></nav></header>
<section v-if="activePage==='home'" class="hero"><main><h1>简单、可靠的数字商品商城</h1><p>精选商品，快速下单，游客也能咨询客服。</p></main></section>
<main><section v-if="activePage==='home'"><h2>精选商品</h2><div class="grid"><article v-for="p in products" :key="p.id"><div class="product-image product-link" @click="openDetail(p)"><img v-if="p.image_url" :src="p.image_url" :alt="p.name"><span v-else>{{p.name.slice(0,1)}}</span></div><h3 class="product-link" @click="openDetail(p)">{{p.name}}</h3><p>{{p.description}}</p><b>¥ {{p.price}}</b><del v-if="p.original_price">¥ {{p.original_price}}</del><small>库存 {{p.stock}}</small><div><button class="buy-button" @click="openDetail(p)">立即购买</button><button class="cart-button" @click="add(p)">加入购物车</button></div></article></div></section>
<section id="cart" v-if="activePage==='cart'" class="cart"><h2>购物车</h2><div v-if="!cartRows.length">购物车为空</div><div v-for="i in cartRows" :key="i.product_id" class="cart-row"><span>{{i.product.name}}</span><span>¥{{Number(i.product.price).toFixed(2)}} × <button @click="setQty(i.product_id,i.quantity-1)">−</button><input type="number" :value="i.quantity" @change="setQty(i.product_id,$event.target.value)"><button @click="setQty(i.product_id,i.quantity+1)">＋</button></span><strong>¥{{i.subtotal.toFixed(2)}}</strong><button @click="remove(i.product_id)">删除</button></div><div class="cart-total">合计：<b>¥{{total.toFixed(2)}}</b><button @click="checkout">提交订单</button></div></section>
<section v-if="activePage==='mine'" class="cart"><h2>我的订单</h2><button v-if="!authToken" @click="showAuthPanel">登录 / 注册</button><div v-if="authToken&&!orders.length">暂无订单</div><div v-for="o in orders" :key="o.id">{{o.order_no}}　¥{{o.total_amount}}　{{o.status}}</div></section>
<section v-if="activePage==='service'" class="service-page">
  <div class="service-intro"><div><span class="service-kicker">CUSTOMER CARE</span><h1>在线客服</h1><p>遇到问题？请发送消息联系我们</p></div></div>
  <div class="service-layout">
    <aside class="service-sidebar"><h3>常见问题</h3><button v-for="q in ['如何查看订单状态？','支付后多久发货？','如何申请退款？','商品可以开发票吗？']" :key="q" :disabled="chatSending" @click="sendQuick(q)">{{q}}<span>›</span></button><div class="sidebar-tip"><span>✦</span><div><b>需要人工帮助？</b><small>点击问题或直接发送消息</small></div></div></aside>
    <div class="service-chat-panel">
      <div class="chat-panel-head"><button class="mobile-chat-back" aria-label="返回" @click="leaveService">‹</button><div class="agent-avatar">客</div><div><b>轻量商城客服</b></div></div>
      <div ref="chatMessagesEl" class="messages service-messages"><div class="chat-date">今天</div><div v-if="chatError" class="chat-error">{{chatError}} <button @click="openChat">重新连接</button></div><div class="system-note">欢迎来到轻量商城，很高兴为你服务</div><p v-for="m in messages" :class="m.sender" :key="m.id">{{m.content}}<small v-if="m.created_at">{{new Date(m.created_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}}</small></p></div>
      <div class="quick-replies"><button v-for="q in ['查订单','退款政策','配送时效']" :key="q" :disabled="!chatReady||chatSending" @click="sendQuick(q)">{{q}}</button></div>
      <div class="chat-compose"><input v-model="message" :disabled="!chatReady||chatSending" @keyup.enter="send" placeholder="请输入消息"><button class="send-btn" :disabled="!chatReady||chatSending||!message.trim()" @click="send">{{chatSending?'发送中':'发送'}}</button></div>
      <small class="chat-security">消息仅用于本次客服沟通</small>
    </div>
  </div>
</section></main>
<button v-if="activePage==='home'" class="chat-fab" @click="navService">在线客服</button>
<div v-if="selected" class="product-detail-screen"><div class="detail-topbar"><button @click="selected=null" aria-label="返回">‹</button><span>商品详情</span><button @click="shareProduct" aria-label="分享">↗</button></div><div class="detail-gallery"><div class="product-image large"><img v-if="selected.image_url" :src="selected.image_url" :alt="selected.name"><span v-else>{{selected.name.slice(0,1)}}</span></div><div class="gallery-count">1 / 1</div></div><div class="detail-content"><div class="detail-price"><b>¥{{selected.price}}</b><del v-if="selected.original_price">¥{{selected.original_price}}</del><span>已售 {{selected.sales??0}}</span></div><h2>{{selected.name}}</h2><p class="detail-description">{{selected.description}}</p><div class="detail-tags"><span>正品保障</span><span>极速发货</span><span>售后无忧</span></div><div class="detail-row"><span>配送</span><b>默认快递 · 预计 1-3 天送达</b><i>›</i></div><div class="detail-row"><span>服务</span><b>支持在线客服 · 订单保障</b><i>›</i></div><div class="detail-quantity"><span>购买数量</span><div><button @click="detailQty=Math.max(1,detailQty-1)">−</button><input type="number" v-model.number="detailQty" :min="1" :max="selected.stock"><button @click="detailQty=Math.min(selected.stock,detailQty+1)">＋</button></div></div></div><div class="detail-actions"><button class="detail-service" @click="openDetailChat" aria-label="联系客服"><svg class="detail-service-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 13v-1a8 8 0 0 1 16 0v1"/><path d="M4 13a2 2 0 0 0 2 2h1v-5H6a2 2 0 0 0-2 2Zm16 0a2 2 0 0 1-2 2h-1v-5h1a2 2 0 0 1 2 2Z"/><path d="M15 19h-2a2 2 0 0 1-2-2"/></svg><small>客服</small></button><button class="detail-cart" @click="add(selected,detailQty);selected=null">加入购物车</button><button class="detail-buy" @click="buyNow">立即支付</button></div></div>
<div v-if="showAuth" class="modal"><div class="modal-card auth-card"><button class="close" @click="showAuth=false">×</button><h2>{{authMode==='login'?'登录':'注册'}}</h2><div class="auth-tabs" role="tablist"><button :class="{active:authMode==='login'}" @click="setAuthMode('login')">登录</button><button :class="{active:authMode==='register'}" @click="setAuthMode('register')">注册</button></div><input v-model="username" placeholder="用户名" autocomplete="username"><input v-model="password" type="password" placeholder="密码" :autocomplete="authMode==='register'?'new-password':'current-password'"><div v-if="authMode==='register'" class="captcha-field"><input v-model="captchaCode" placeholder="请输入验证码" maxlength="8" autocomplete="off" @keyup.enter="auth('register')"><button type="button" class="captcha-image-button" :disabled="captchaLoading" @click="loadCaptcha" :aria-label="captchaLoading?'验证码加载中':'刷新验证码'"><img v-if="captchaImage&&!captchaLoading" :src="captchaImage" alt="验证码"><span v-else>加载中…</span></button></div><button class="auth-submit" :disabled="authSubmitting" @click="auth()">{{authSubmitting?'提交中…':authMode==='login'?'登录':'注册'}}</button></div></div>
<div v-if="notice.visible" class="notice-modal" role="presentation" tabindex="-1" @click.self="closeNotice" @keydown.esc="closeNotice"><div class="notice-card" :class="`notice-${notice.type}`" role="dialog" aria-modal="true" aria-labelledby="notice-title" aria-describedby="notice-message"><div class="notice-icon" aria-hidden="true">{{notice.type==='success'?'✓':notice.type==='warning'?'!':notice.type==='error'?'×':'i'}}</div><div class="notice-copy"><h2 id="notice-title">{{notice.title}}</h2><p id="notice-message">{{notice.message}}</p></div><button class="notice-close" aria-label="关闭提示" @click="closeNotice">×</button><button class="notice-action" @click="closeNotice">知道了</button></div></div>
<div v-if="chatOpen && activePage!=='service'" class="chat service-chat"><b>在线客服 <button @click="chatOpen=false;activePage='home'">×</button></b><div class="messages"><p v-for="m in messages" :class="m.sender" :key="m.id">{{m.content}}</p></div><input v-model="message" @keyup.enter="send" placeholder="请输入问题"><button @click="send">发送</button></div>
<nav v-if="activePage!=='service'" class="mobile-bottom-nav" aria-label="移动端导航"><button :class="{active:activePage==='home'}" @click="navHome"><span>⌂</span><small>首页</small></button><button :class="{active:activePage==='cart'}" @click="navCart"><span>🛒<i v-if="cartRows.length">{{cartRows.length}}</i></span><small>购物车</small></button><button @click="navService"><span>◌</span><small>客服</small></button><button :class="{active:activePage==='mine'}" @click="navMine"><span>♙</span><small>我的</small></button></nav>
</template>

